name: Create changelog

on:
  workflow_dispatch:

jobs:
  Create-changelog:
    runs-on: ubuntu-latest
    steps:
      - name: Create Release
        uses: ncipollo/release-action@v1
        id: create_release
        with:
          tag: "1.0.10"
          token: ${{ secrets.GITHUB_TOKEN }}
          generateReleaseNotes: true
